Models/DatabaseConnection.cs
using System;

namespace GroupWebApplication.Models
{
    public class DatabaseConnection
    {
        public readonly string ConnectionString = "Server=tcp:csd412project.database.windows.net,1433;" +
                                                  "Initial Catalog=NasaProject;Persist Security Info=False;" +
                                                  "User ID=[];Password=[];MultipleActiveResultSets=False;" +
                                                  "Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
    }
}

Models/ErrorViewModel.cs
using System;

namespace GroupWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroupWebApplication.Models
{
    public class Home
    {
        public String Date { get; set; }
        public String Explanation { get; set; }
        public String Title { get; set; }
        public String Url { get; set; }
    }
}

Models/ImageModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GroupWebApplication.Models
{
    public class ImageModel
    {
        [Key]
        public String Date { get; set; }
        public String Explanation { get; set; }
        public String MediaType { get; set; }
        public String Title { get; set; }
        public String Url { get; set; }
        public String Hdurl { get; set; }
    }
}

Models/VoteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GroupWebApplication.Models
{
    public class VoteModel
    {
        [Key]
        public String Date { get; set; } //ImageID = Date Value
        public int Votes { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using GroupWebApplication.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GroupWebApplication.Models;


namespace GroupWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            /* Gets current date and pulls image for current date from database. If current date media type
             * isn't an image, moves to previous day to get image.
             */
            String todayDate = DateTime.Today.ToUniversalTime().ToString("yyyy-MM-dd");

            ImageModel imgModel;

            using (var context = new AzureImageContext())
            {
                imgModel = context.imagedbcontext.Single(a => a.Date == todayDate);
                
                var i = -1;
                while (imgModel == null || imgModel.MediaType != "image")
                {
                    String adjDate = DateTime.Today.AddDays(i).ToString("yyyy-MM-dd");
                    imgModel = context.imagedbcontext.Single(a => a.Date == adjDate);
                    i--;
                }
            }

            return View(imgModel);
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GroupWebApplication.Data;
using GroupWebApplication.Models;
using Microsoft.AspNetCore.Mvc;

namespace GroupWebApplication.Controllers
{
    public class ImageController : Controller
    {
        // GET
        // Get all data with image media type
        public IActionResult Index()
        {
            String mediaType = "image";
            List<ImageModel> imgModel = new List<ImageModel>();

            using (var context = new AzureImageContext())
            {
                var images = context.imagedbcontext;

                foreach (var image in images)
                {
                    if (image.MediaType == mediaType)
                    {
                        imgModel.Add(image);
                    }
                }
            }

            imgModel = imgModel.OrderByDescending(d => d.Date).ToList();

            return View(imgModel);
        }

        /*
        public IActionResult Index()
        {
            String mediaType = "image";
            //var imageVoteModels;

            ImageVoteModel context = new ImageVoteModel();
            {
                
                IQueryable<ImageVoteModel> imageVoteModels = from i in context.imageModel
                    join v in context.voteModel
                        on i.Date equals v.Date
                    orderby i.Date
                    where i.Media_Type == "images"
                    select new ImageVoteModel
                    {
                        Date = i.Date, Explanation = i.Explanation,
                        Hdurl = i.Hdurl, Url = i.Url, Media_Type = i.Media_Type,
                        Title = i.Title, Votes = v.Votes
                    };

                var imageList = imageVoteModels.ToList();

                return View(imageList);
            }
        }*/
    }
}

Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GroupWebApplication.Data;
using GroupWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;


namespace GroupWebApplication.Controllers
{
    public class VideoController : Controller
    {
        // GET
        // Get all data with video media type
        public IActionResult Index()
        {
            String mediaType = "video";
            List<ImageModel> videoModel = new List<ImageModel>();

            using (var context = new AzureImageContext())
            {
                var videos = context.imagedbcontext;

                foreach (var video in videos)
                {
                    if (video.MediaType == mediaType)
                    {
                        videoModel.Add(video);
                    }
                }
            }

            videoModel = videoModel.OrderByDescending(d => d.Date).ToList();

            return View(videoModel);
        }
    }
}

Views/Data/Index.cshtml
@model IEnumerable<GroupWebApplication.Models.ImageModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Explanation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Explanation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
           
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@using System.Diagnostics.CodeAnalysis
@using Microsoft.EntityFrameworkCore.Infrastructure
@using SQLitePCL
@model GroupWebApplication.Models.ImageModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h2 class="display-4">Welcome To Our NASA Collection</h2>
    <!-- Home image is based on current date image provided from the NASA API for daily images. -->
    <img src="@Html.DisplayFor(Model => Model.Url)" alt="@Html.DisplayFor(Model => Model.Title)">
</div>

Views/Image/Index.cshtml
@using System.Runtime.InteropServices
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model List<ImageModel>

 @{
     ViewData["Title"] = "Images";
 }

 <h1>Nasa Daily Images</h1>

<table class="table">
    <tbody>
    @{ var column = 0; }
    <!-- Iterates through image model from database. Displays images with title and date. 
            Puts image set in a 3 column width.-->
    @foreach (var image in Model)
    {
        @if (column == 0)
        {
            @Html.Raw("<tr>");
        }

        <td>
            <img src="@Html.DisplayFor(model => image.Url)"
                 alt="@Html.DisplayFor(model => image.Title)"
                 width="350" height="196"
                 onclick="location.href='@Html.DisplayFor(model => image.Url)'"/>
            <h5>@Html.DisplayFor(model => image.Title)</h5>
            <div style="float: left">
                <h5>@Html.DisplayFor(model => image.Date)</h5>
            </div>
            <div style="float: right">
                <a href="@Html.DisplayFor(model => image.Hdurl)" target="_blank">
                    <b>HD Link</b>
                </a>
            </div>
        </td>
        
        if (column == 2)
        {
            @Html.Raw("</tr>");
            column = 0;
        }
        else
        {
            column++;
        }
    }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSD412 Group Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="/logos/nasalogo.png" alt="nasalogo"/>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"/>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Index">Image</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Index">Video</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Bear Bare Design - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Video/Index.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
 @model IEnumerable<GroupWebApplication.Models.ImageModel>

 @{
     ViewData["Title"] = "Videos";
 }

 <h1>Nasa Daily Videos</h1>

 <table class="table">
     <tbody>
     <!-- Iterates through image video model and displays video link, title, date and explanation of video. -->
     @foreach (var video in Model)
     {
         <tr>
             <td>
                 <iframe width="500"
                         height="281"
                         src="@Html.DisplayFor(model => video.Url)"
                         allowfullscreen></iframe>
             </td>
             <td>
                 <h4>@Html.DisplayFor(model => video.Title)</h4>
                 <h5>@Html.DisplayFor(model => video.Date)</h5>
                 @Html.DisplayFor(model => video.Explanation)
             </td>
         </tr>
     }
     </tbody>
 </table> 